# .github/workflows/bot.yml

name: Run Telegram Bot

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      USER_ACCESS: ${{ secrets.USER_ACCESS }}
      START_MESSAGE_FILE: ${{ secrets.START_MESSAGE_FILE }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Environment Variables
        run: |
          if [ -z "$USER_ACCESS" ]; then
            echo "USER_ACCESS is not set"
            exit 1
          else
            echo "USER_ACCESS is set"
          fi

      - name: Run Bot
        run: |
          python setup.py
